all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.T000001/Hello
#	java -classpath "../.." s4.T000001/Frequencer
#	java -classpath "../.." s4.T000001/InformationEstimator
	java -classpath "../.." s4.T000001/TestCase
