all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.Sample1/Hello
#	java -classpath "../.." s4.Sample1/Frequencer
#	java -classpath "../.." s4.Sample1/InformationEstimator
	java -classpath "../.." s4.Sample1/TestCase
