all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4/buggy/Hello
#	java -classpath "../.." s4/buggy/Frequencer
#	java -classpath "../.." s4/buggy/InformationEstimator
	java -classpath "../.." s4/buggy/TestCase
