all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.T000002/Hello
#	java -classpath "../.." s4.T000002/Frequencer
#	java -classpath "../.." s4.T000002/InformationEstimator
	java -classpath "../.." s4.T000002/TestCase
