all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B193337/Hello
#	java -classpath "../.." s4.B193337/Frequencer
#	java -classpath "../.." s4.B193337/InformationEstimator
	java -classpath "../.." s4.B193337/TestCase
