all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.T000005/Hello
#	java -classpath "../.." s4.T000005/Frequencer
#	java -classpath "../.." s4.T000005/InformationEstimator
	java -classpath "../.." s4.T000005/TestCase
