all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B171848/Hello
#	java -classpath "../.." s4.B171848/Frequencer
#	java -classpath "../.." s4.B171848/InformationEstimator
	java -classpath "../.." s4.B171848/TestCase
