all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B161822/Hello
#	java -classpath "../.." s4.B161822/Frequencer
#	java -classpath "../.." s4.B161822/InformationEstimator
	java -classpath "../.." s4.B161822/TestCase
