all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B171809/Hello
#	java -classpath "../.." s4.B171809/Frequencer
#	java -classpath "../.." s4.B171809/InformationEstimator
	java -classpath "../.." s4.B171809/TestCase
