all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B193303/Hello
#	java -classpath "../.." s4.B193303/Frequencer
#	java -classpath "../.." s4.B193303/InformationEstimator
	java -classpath "../.." s4.B193303/TestCase
