all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B171811/Hello
#	java -classpath "../.." s4.B171811/Frequencer
#	java -classpath "../.." s4.B171811/InformationEstimator
	java -classpath "../.." s4.B171811/TestCase
