all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.Sample2/Hello
#	java -classpath "../.." s4.Sample2/Frequencer
#	java -classpath "../.." s4.Sample2/InformationEstimator
	java -classpath "../.." s4.Sample2/TestCase
