all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.T000006/Hello
#	java -classpath "../.." s4.T000006/Frequencer
#	java -classpath "../.." s4.T000006/InformationEstimator
	java -classpath "../.." s4.T000006/TestCase
