all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.Sample3/Hello
#	java -classpath "../.." s4.Sample3/Frequencer
#	java -classpath "../.." s4.Sample3/InformationEstimator
	java -classpath "../.." s4.Sample3/TestCase
