all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B171304/Hello
#	java -classpath "../.." s4.B171304/Frequencer
#	java -classpath "../.." s4.B171304/InformationEstimator
	java -classpath "../.." s4.B171304/TestCase
