all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B171836/Hello
#	java -classpath "../.." s4.B171836/Frequencer
#	java -classpath "../.." s4.B171836/InformationEstimator
	java -classpath "../.." s4.B171836/TestCase
