all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.Sample4/Hello
#	java -classpath "../.." s4.Sample4/Frequencer
#	java -classpath "../.." s4.Sample4/InformationEstimator
	java -classpath "../.." s4.Sample4/TestCase
