all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B193368/Hello
#	java -classpath "../.." s4.B193368/Frequencer
#	java -classpath "../.." s4.B193368/InformationEstimator
	java -classpath "../.." s4.B193368/TestCase
