all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 ../umemura/TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B193369/Hello
	java -classpath "../.." s4.B193369/Frequencer
	java -classpath "../.." s4.B193369/InformationEstimator
#	java -classpath "../.." s4.B193369/TestCase
