all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
	java -classpath "../.." s4.B193369/Hello
	java -classpath "../.." s4.B193369/Frequencer
	java -classpath "../.." s4.B193369/InformationEstimator
	java -classpath "../.." s4.B193369/TestCase
